spring:
  application:
       name: demo

  datasource:
       url: ${DB_URL}
       username: ${DB_UNAME}
       password: ${DB_PASS}
       driver-class-name: ${DRIVER_CLASS}

# Hibernate JPA properties
  jpa:
         hibernate.ddl-auto: update
         show-sql: true
         properties:
              hibernate:
                    format_sql: true
                    highlight_sql: true


  mail:
     host: ${SMTP_HOST}
     port: ${SMTP_PORT}
     username: ${SMTP_UNAME}
     password: ${SMTP_PASS}
     properties:
        mail:
          smtp:
            auth: true
            starttls:
               enable: true

logging:
  file:
    name: logs/app.log

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP} # in milliseconds

app:
  ip: ${HOST_IP}



