INSERT INTO template (name, type, content)
VALUES
("Formal Invitation", "FORMAL", "Dear [GuestName],\n\nWe are delighted to invite you to the prestigious event, [EventName], held at [EventLocation] on [EventDate]. Kindly RSVP by [RSVPDate].\n\nWarm regards,\n[OrganizerName]"),
("Casual Gathering Invitation", "CASUAL", "Hey [GuestName],\n\nJoin us for [EventName], a fun get-together happening at [EventLocation] on [EventDate]. Please RSVP by [RSVPDate]!\n\nBest,\n[OrganizerName]"),
("Corporate Conference Invitation", "CORPORATE", "Dear [GuestName],\n\nYou're invited to attend [EventName], a professional conference taking place at [EventLocation] on [EventDate]. Kindly confirm your attendance by [RSVPDate].\n\nSincerely,\n[OrganizerName]"),
("Wedding Invitation", "WEDDING", "Dear [GuestName],\n\nWe would be honored to have you at the wedding of [EventName] on [EventDate], which will take place at [EventLocation]. Please RSVP by [RSVPDate].\n\nWith love,\n[OrganizerName]"),
("Birthday Party Invitation", "BIRTHDAY", "Hi [GuestName],\n\nCelebrate [EventName] with us on [EventDate] at [EventLocation]. Don't forget to RSVP by [RSVPDate] to join in the fun!\n\nCheers,\n[OrganizerName]"),
("Charity Event Invitation", "CHARITY", "Dear [GuestName],\n\nYou are cordially invited to [EventName] in support of a noble cause. The event will take place at [EventLocation] on [EventDate]. Please RSVP by [RSVPDate].\n\nWarm regards,\n[OrganizerName]"),
("Graduation Ceremony Invitation", "GRADUATION", "Dear [GuestName],\n\nJoin us as we celebrate the graduation of [EventName] on [EventDate], held at [EventLocation]. Kindly RSVP by [RSVPDate].\n\nSincerely,\n[OrganizerName]"),
("Product Launch Invitation", "LAUNCH", "Hello [GuestName],\n\nWe are excited to invite you to the launch of [EventName] on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to confirm your participation.\n\nBest regards,\n[OrganizerName]"),
("Networking Event Invitation", "NETWORKING", "Dear [GuestName],\n\nWe invite you to join us for [EventName], a fantastic networking opportunity at [EventLocation] on [EventDate]. Please RSVP by [RSVPDate].\n\nKind regards,\n[OrganizerName]"),
("Awards Ceremony Invitation", "AWARDS", "Dear [GuestName],\n\nWe are pleased to invite you to the [EventName] taking place on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to attend.\n\nSincerely,\n[OrganizerName]")
("Team Building Invitation", "TEAM_BUILDING", "Dear [GuestName],\n\nWe invite you to a fun-filled team-building event, [EventName], on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate].\n\nBest regards,\n[OrganizerName]"),
("Holiday Party Invitation", "HOLIDAY_PARTY", "Hi [GuestName],\n\nCelebrate the holiday season with us at [EventName] on [EventDate] at [EventLocation]. Kindly RSVP by [RSVPDate].\n\nCheers,\n[OrganizerName]"),
("Music Festival Invitation", "MUSIC_FESTIVAL", "Dear [GuestName],\n\nGet ready for an unforgettable experience at [EventName], a music festival on [EventDate] at [EventLocation]. RSVP by [RSVPDate] to secure your spot!\n\nSee you there,\n[OrganizerName]"),
("New Year Celebration Invitation", "NEW_YEAR", "Dear [GuestName],\n\nRing in the new year with us at [EventName] on [EventDate], held at [EventLocation]. Please RSVP by [RSVPDate].\n\nWarm wishes,\n[OrganizerName]"),
("Fashion Show Invitation", "FASHION_SHOW", "Dear [GuestName],\n\nWe would be honored to have you at [EventName], a stylish fashion show on [EventDate] at [EventLocation]. Kindly RSVP by [RSVPDate].\n\nBest regards,\n[OrganizerName]"),
("Sports Tournament Invitation", "SPORTS_TOURNAMENT", "Dear [GuestName],\n\nJoin us for [EventName], an exciting sports tournament happening on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to confirm your attendance.\n\nRegards,\n[OrganizerName]"),
("Book Club Meeting Invitation", "BOOK_CLUB", "Hi [GuestName],\n\nYou're invited to our next book club meeting, [EventName], on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to join the discussion.\n\nBest regards,\n[OrganizerName]"),
("Art Exhibition Invitation", "ART_EXHIBITION", "Dear [GuestName],\n\nWe are pleased to invite you to the [EventName] art exhibition on [EventDate] at [EventLocation]. Kindly RSVP by [RSVPDate] to secure your attendance.\n\nSincerely,\n[OrganizerName]"),
("Movie Premiere Invitation", "MOVIE_PREMIERE", "Dear [GuestName],\n\nYou're invited to the exclusive premiere of [EventName] on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to attend this special event.\n\nLooking forward,\n[OrganizerName]"),
("Summer Picnic Invitation", "SUMMER_PICNIC", "Hi [GuestName],\n\nJoin us for a relaxing day at [EventName] on [EventDate] at [EventLocation]. Please RSVP by [RSVPDate] to confirm your attendance.\n\nWarmly,\n[OrganizerName]");

